
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS form_responses (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER,
	response_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	score INTEGER,
	FOREIGN KEY(user_id) REFERENCES users(id)
);