CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_name TEXT NOT NULL UNIQUE,
	team INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS form_responses (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER,
	sending_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	response_time DATETIME DEFAULT NULL,
	score FLOAT DEFAULT -1,
	FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS questions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	form_id INTEGER,
	question TEXT DEFAULT NULL,
	answer TEXT DEFAULT NULL,
	FOREIGN KEY(form_id) REFERENCES form_responses(id)
);