CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS form_responses (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER,
	sending_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	response_time DATETIME DEFAULT NULL,
	score FLOAT DEFAULT -1,
	FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS questions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	question TEXT DEFAULT NULL,
	answer TEXT DEFAULT NULL
);